{{- if .Values.postgres.enabled }}
{{- $ctx := dict "root" . "component" "postgres" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.postgresSecretName" . }}
  namespace: {{ include "user-mgmt.namespace" . }}
  labels:
    {{- include "user-mgmt.labels" $ctx | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
