{{- if .Values.postgres.enabled }}
{{- $ctx := dict "root" . "component" "postgres" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-mgmt.componentName" $ctx }}
  namespace: {{ include "user-mgmt.namespace" . }}
  labels:
    {{- include "user-mgmt.labels" $ctx | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    {{- include "user-mgmt.selectorLabels" $ctx | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- end }}
