{{- if .Values.backend.enabled }}
{{- $ctx := dict "root" . "component" "backend" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.componentName" $ctx }}
  namespace: {{ include "user-mgmt.namespace" . }}
  labels:
    {{- include "user-mgmt.labels" $ctx | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
